import type { Bibliography } from '../types';

export const masterBibliography: Bibliography = {
    "Geral": [
        { "title": "My System", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Um clássico fundamental de Aron Nimzowitsch que introduziu conceitos posicionais revolucionários como a profilaxia, o bloqueio e a superproteção. Leitura essencial para entender a estratégia moderna." },
        { "title": "The Art of Attack in Chess", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "A obra-prima de Vladimir Vuković sobre a arte de atacar o rei. O livro disseca os pré-requisitos, os motivos e a execução de ataques, tornando-se um guia atemporal para jogadores agressivos." },
        { "title": "Judgment and Planning in Chess", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "O ex-campeão mundial Max Euwe explica como avaliar uma posição e formular um plano com base nessa avaliação. Um guia claro e sistemático sobre o pensamento posicional." },
        { "title": "Think Like a Grandmaster", "min": 2000, "max": 2600, "difficulty": 2, "synopsis": "Alexander Kotov explora o processo de pensamento de um Grande Mestre, focando em como analisar posições complexas, identificar lances candidatos e tomar decisões sob pressão." },
        { "title": "Yusupov Training Series - Vol. 1-3 (Fundamentals)", "min": 1400, "max": 2200, "difficulty": 2, "synopsis": "O início da aclamada série de 9 volumes de Artur Yusupov. Cobre todos os aspectos do jogo (tática, estratégia, finais) de forma estruturada, com lições e exercícios." },
        { "title": "Yusupov Training Series - Vol. 4-6 (Beyond the Basics)", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "Inicia o segundo nível (avançado) da série, elevando a complexidade dos exercícios e introduzindo conceitos estratégicos e de cálculo mais sutis." },
        { "title": "Yusupov Training Series - Vol. 7-9 (Mastery)", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "O nível de maestria da série de Yusupov, projetado para refinar a habilidade de jogadores fortes e prepará-los para o nível de mestre com desafios complexos." },
        { "title": "Grandmaster Preparation - Positional Play", "min": 2200, "max": 2600, "difficulty": 4, "synopsis": "O volume de Jogo Posicional da série de Jacob Aagaard, ensinando a arte de melhorar a posição de suas peças e criar planos de longo prazo através de exercícios desafiadores." },
        { "title": "Grandmaster Preparation - Strategic Play", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "Dedicado ao Pensamento Estratégico, este livro ensina como tomar decisões complexas, gerenciar o tempo e entender a psicologia da competição no mais alto nível." },
        { "title": "Grandmaster Preparation - Attack and Defence", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "Uma exploração profunda da interação entre ataque e defesa. Aagaard usa exemplos complexos para treinar a intuição e a precisão em posições de dois gumes." },
        { "title": "Positional Decision Making in Chess", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "Boris Gelfand compartilha sua profunda sabedoria posicional, analisando temas como o 'efeito polvo', o jogo com vantagem de espaço e a tomada de decisões em posições complexas." },
        { "title": "Technical Decision Making in Chess", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "No segundo volume de sua série, Gelfand foca na técnica de conversão de vantagens. Ele explora como transformar uma vantagem posicional ou material em uma vitória." },
        { "title": "Maneuvering: The Art of Piece Play", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "Mark Dvoretsky foca na arte de melhorar a posição das peças através de manobras sutis. Um guia essencial para entender a harmonia e o potencial das peças." },
        { "title": "Grandmaster Preparation - Vol. 1", "min": 1800, "max": 2200, "difficulty": 4 },
        { "title": "Grandmaster Preparation - Vol. 2", "min": 1800, "max": 2200, "difficulty": 4 },
        { "title": "Grandmaster Preparation - Vol. 3", "min": 1800, "max": 2200, "difficulty": 4 },
        { "title": "Grandmaster Preparation - Vol. 4", "min": 2000, "max": 2600, "difficulty": 4 },
        { "title": "Grandmaster Preparation - Vol. 5", "min": 2000, "max": 2600, "difficulty": 4 },
        { "title": "Grandmaster Preparation - Vol. 6", "min": 2000, "max": 2600, "difficulty": 4 }
    ],
    "Tática": [
        { "title": "The Art of Combination", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Um clássico de Eugene Znosko-Borovsky que ensina os elementos fundamentais das combinações de xadrez de uma forma clara e concisa. Perfeito para construir uma base tática sólida." },
        { "title": "Winning Chess Tactics", "min": 1200, "max": 1800, "difficulty": 1, "synopsis": "Parte da popular série 'Winning Chess' de Yasser Seirawan, este livro introduz os temas táticos fundamentais de forma clara e acessível, ideal para iniciantes e jogadores de clube." },
        { "title": "The Woodpecker Method", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "Axel Smith e Hans Tikkanen apresentam um método de treinamento tático baseado na repetição de exercícios em ciclos cada vez mais rápidos para internalizar padrões e aumentar a velocidade de cálculo." },
        { "title": "Encyclopedia of Chess Combinations", "min": 1400, "max": 2600, "difficulty": 3, "synopsis": "Uma vasta coleção de mais de 3000 exercícios táticos, classificados por tema. Uma ferramenta indispensável para o treinamento tático sistemático em todos os níveis." },
        { "title": "Forcing Chess Moves", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "Charles Hertan introduz o conceito de 'Lances Forçados', ensinando um método para encontrar combinações brilhantes e inesperadas que muitos jogadores deixariam passar." },
        { "title": "Imagination in Chess", "min": 2000, "max": 2400, "difficulty": 3, "synopsis": "Uma coleção de exercícios desafiadores para desenvolver a criatividade e a imaginação tática, compilados pela ex-campeã mundial Nona Gaprindashvili." },
        { "title": "Shirov – Fire on Board (Vol. I & II)", "min": 2200, "max": 2600, "difficulty": 4, "synopsis": "Uma coleção das melhores partidas de Alexei Shirov, conhecido por seu estilo de ataque feroz e sacrifícios brilhantes. Um banquete para amantes do xadrez dinâmico." }
    ],
    "Cálculo": [
        { "title": "Grandmaster Preparation - Calculation", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "O livro mais famoso da série de Jacob Aagaard. Apresenta exercícios de cálculo extremamente difíceis, projetados para levar a habilidade de análise e visualização a um nível de elite." },
        { "title": "Perfect Your Chess", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "Andrei Volokitin e Vladimir Grabinsky oferecem um curso de treinamento com 24 lições e 400 exercícios para melhorar o cálculo, a tática e o jogo dinâmico." },
        { "title": "Recognizing Your Opponent's Resources", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "Um aspecto crucial do cálculo de alto nível. Mark Dvoretsky ensina a arte da profilaxia e a importância de considerar os recursos e contra-jogo do oponente durante a análise." },
        { "title": "The Inner Game of Chess: How to Calculate and Choose the Best Move", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Andrew Soltis detalha um processo de pensamento estruturado para o cálculo, ensinando como podar a árvore de análise, evitar erros de cálculo e gerenciar o tempo de forma eficaz." }
    ],
    "Partidas": [
        { "title": "My 60 Memorable Games", "min": 1800, "max": 9999, "difficulty": 3, "synopsis": "Considerado por muitos o melhor livro de xadrez já escrito. Bobby Fischer analisa suas 60 melhores partidas com uma honestidade e profundidade sem precedentes. Leitura obrigatória." },
        { "title": "The Life and Games of Mikhail Tal", "min": 2000, "max": 2600, "difficulty": 3, "synopsis": "A autobiografia do 'Mágico de Riga', repleta de partidas incríveis, anedotas fascinantes e análises que capturam seu gênio tático e estilo de sacrifício." },
        { "title": "Zurich International Chess Tournament, 1953", "min": 2000, "max": 2600, "difficulty": 3, "synopsis": "David Bronstein analisa todas as 210 partidas do lendário Torneio de Candidatos de 1953. Uma obra-prima que oferece lições profundas sobre estratégia e o fluxo de uma partida." },
        { "title": "Kasparov's My Great Predecessors (Series)", "min": 2200, "max": 2800, "difficulty": 4, "synopsis": "A obra-prima de Garry Kasparov em 5 volumes, analisando a vida e as partidas de todos os campeões mundiais de Steinitz a Karpov, com a profundidade analítica de um dos maiores de todos os tempos." },
        { "title": "Alekhine's Best Games of Chess (1908-1945)", "min": 1800, "max": 2500, "difficulty": 3, "synopsis": "Uma coleção das melhores partidas do quarto campeão mundial, analisadas por ele mesmo. Um vislumbre de seu estilo de ataque complexo e dinâmico." },
        { "title": "Botvinnik: One Hundred Selected Games", "min": 1800, "max": 2500, "difficulty": 3, "synopsis": "O patriarca da escola soviética de xadrez analisa 100 de suas próprias partidas, revelando sua abordagem lógica, científica e profundamente estratégica para o jogo." },
        { "title": "Understanding Chess Move by Move", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "John Nunn seleciona 30 partidas de Grandes Mestres e explica a lógica por trás de cada lance, tornando a estratégia de alto nível acessível para jogadores de clube." },
        { "title": "Logical Chess: Move by Move", "min": 1200, "max": 1800, "difficulty": 1, "synopsis": "Irving Chernev explica 33 partidas clássicas, detalhando o propósito de cada lance. Perfeito para iniciantes e jogadores que buscam entender os princípios básicos da estratégia." },
        { "title": "Lessons with a Grandmaster - Vol. 1", "min": 1800, "max": 2400, "difficulty": 4 },
        { "title": "Lessons with a Grandmaster - Vol. 2", "min": 1800, "max": 2400, "difficulty": 4 },
        { "title": "Lessons with a Grandmaster - Vol. 3", "min": 1800, "max": 2400, "difficulty": 4 },
        { "title": "Lessons with a Grandmaster - Vol. 4", "min": 1800, "max": 2400, "difficulty": 4 },
        { "title": "Grandmaster Games Anthology - Vol. 1", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 2", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 3", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 4", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 5", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 6", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 7", "min": 2000, "max": 2600, "difficulty": 3 },
        { "title": "Grandmaster Games Anthology - Vol. 8", "min": 2000, "max": 2600, "difficulty": 3 }
    ],
    "Finais": [
        { "title": "Silman's Complete Endgame Course", "min": 1000, "max": 2400, "difficulty": 2, "synopsis": "Jeremy Silman estrutura o aprendizado de finais por faixas de rating, garantindo que o jogador aprenda apenas o que é necessário para seu nível atual. Abordagem revolucionária e muito prática." },
        { "title": "Dvoretsky's Endgame Manual", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "Provavelmente o livro de finais mais completo e respeitado. Uma obra de referência essencial para qualquer jogador sério que deseja alcançar a maestria em finais." },
        { "title": "Fundamental Chess Endings", "min": 1800, "max": 2500, "difficulty": 3, "synopsis": "Karsten Müller e Frank Lamprecht oferecem uma enciclopédia abrangente de finais teóricos. Menos intimidador que o de Dvoretsky, mas igualmente rigoroso." },
        { "title": "100 Endgames You Must Know", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Jesús de la Villa apresenta os 100 finais teóricos mais importantes que todo jogador de torneio deve conhecer. Um guia prático e direto ao ponto para construir uma base sólida." },
        { "title": "Endgame Strategy", "min": 1800, "max": 2400, "difficulty": 3, "synopsis": "Mikhail Shereshevsky foca nos princípios estratégicos dos finais, como 'não se apresse' e a importância da atividade do rei. Essencial para entender o jogo prático em finais, além da teoria pura." },
        { "title": "Tragicomedy in the Endgame", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "Mark Dvoretsky usa exemplos fascinantes e muitas vezes surpreendentes para ilustrar conceitos complexos de finais, erros típicos e a importância da precisão." },
        { "title": "Grandmaster Preparation - Endgame Play", "min": 2200, "max": 2700, "difficulty": 4, "synopsis": "Jacob Aagaard foca na estratégia e no jogo prático em finais, complementando o conhecimento teórico com exercícios que treinam a tomada de decisão em cenários complexos." },
        { "title": "Dvoretsky's Analytical Manual", "min": 2000, "max": 2400, "difficulty": 4 }
    ],
    "Aberturas": [
        { "title": "Modern Chess Openings (MCO) - 15th Ed.", "min": 1600, "max": 2200, "tags": ["repertorio_completo"], "difficulty": 2, "synopsis": "Uma enciclopédia de aberturas clássica. A 15ª edição oferece uma visão geral de todas as principais aberturas e defesas, servindo como uma excelente referência." },
        { "title": "Fundamental Chess Openings", "min": 1200, "max": 1800, "difficulty": 1, "synopsis": "Paul van der Sterren explica as ideias por trás de todas as principais aberturas. Em vez de memorização de lances, o foco é na compreensão dos planos e estruturas." },
        { "title": "Chess Openings for Black, Explained", "min": 1400, "max": 2000, "difficulty": 2, "synopsis": "Um repertório completo para as Pretas contra 1.e4, 1.d4 e outros. Os autores (Lev Alburt, Roman Dzindzichashvili, Eugene Perelshteyn) focam em sistemas fáceis de aprender e sólidos." },
        { "title": "Chess Openings for White, Explained", "min": 1400, "max": 2000, "difficulty": 2, "synopsis": "A contraparte do livro para as Pretas, oferecendo um repertório completo e coerente para as Brancas, baseado em 1.e4." },
        { "title": "GM Repertoire 1.e4 vs The French, Caro-Kann & Philidor (Negi)", "min": 2200, "max": 2700, "tags": ["francesa", "caro_kann", "e4_e5"], "difficulty": 4, "synopsis": "Parimarjan Negi oferece um repertório de elite para as Brancas contra três das defesas mais populares, com análises profundas e inovadoras." },
        { "title": "GM Repertoire - The Grünfeld Defence (Avrukh)", "min": 2200, "max": 2600, "tags": ["grunfeld"], "difficulty": 4, "synopsis": "Um repertório completo e de classe mundial para as Pretas na Defesa Grünfeld, escrito por um dos maiores teóricos de abertura do nosso tempo, Boris Avrukh." },
        { "title": "Starting Out: The Ruy Lopez", "min": 1200, "max": 1800, "tags": ["e4_e5"], "difficulty": 1, "synopsis": "Uma introdução clara e concisa à Abertura Espanhola. John Shaw explica as principais variantes e os planos estratégicos para ambos os lados." },
        { "title": "Starting Out: The Queen's Gambit Declined", "min": 1200, "max": 1800, "tags": ["d4_d5"], "difficulty": 1, "synopsis": "Neil McDonald guia o leitor através de uma das defesas mais clássicas e sólidas, explicando as ideias chave e as estruturas de peões." },
        { "title": "GM Repertoire 1: 1.d4 Vol 1 (Avrukh)", "min": 2000, "max": 2600, "tags": ["d4_d5", "semi_fechadas"], "difficulty": 4 },
        { "title": "GM Repertoire 2: 1.d4 Vol 2 (Avrukh)", "min": 2000, "max": 2600, "tags": ["india_rei", "grunfeld", "semi_fechadas"], "difficulty": 4 },
        { "title": "GM Repertoire 1A: 1.d4 A Catalã (Avrukh)", "min": 2000, "max": 2600, "tags": ["d4_d5", "semi_fechadas"], "difficulty": 4 },
        { "title": "GM Repertoire 1B: 1.d4 Gambito da Dama (Avrukh)", "min": 2000, "max": 2600, "tags": ["d4_d5"], "difficulty": 4 },
        { "title": "GM Repertoire 2A: Indiana do Rei e Grünfeld (Avrukh)", "min": 2000, "max": 2600, "tags": ["india_rei", "grunfeld"], "difficulty": 4 },
        { "title": "GM Repertoire 3: A Abertura Inglesa Vol 1 (Marin)", "min": 2000, "max": 2600, "tags": ["inglesa", "flanco"], "difficulty": 4 },
        { "title": "GM Repertoire 4: A Abertura Inglesa Vol 2 (Marin)", "min": 2000, "max": 2600, "tags": ["inglesa", "flanco"], "difficulty": 4 },
        { "title": "GM Repertoire 5: A Abertura Inglesa Vol 3 (Marin)", "min": 2000, "max": 2600, "tags": ["inglesa", "flanco"], "difficulty": 4 },
        { "title": "GM Repertoire 6: A Defesa Siciliana (Ftacnik)", "min": 2000, "max": 2600, "tags": ["siciliana"], "difficulty": 4 },
        { "title": "GM Repertoire 6A: Vencendo as Anti-Sicilianas (Kotronias)", "min": 2000, "max": 2600, "tags": ["siciliana"], "difficulty": 4 },
        { "title": "GM Repertoire 7: A Defesa Caro-Kann (Schandorff)", "min": 2000, "max": 2600, "tags": ["caro_kann"], "difficulty": 4 },
        { "title": "GM Repertoire 8: A Defesa Grünfeld Vol 1 (Avrukh)", "min": 2000, "max": 2600, "tags": ["grunfeld"], "difficulty": 4 },
        { "title": "GM Repertoire 9: A Defesa Grünfeld Vol 2 (Avrukh)", "min": 2000, "max": 2600, "tags": ["grunfeld"], "difficulty": 4 },
        { "title": "GM Repertoire 10: A Defesa Tarrasch (Aagaard/Ntirlis)", "min": 2000, "max": 2600, "tags": ["d4_d5"], "difficulty": 4 },
        { "title": "GM Repertoire 11: Vencendo Linhas Secundárias de 1.d4 (Avrukh)", "min": 2000, "max": 2600, "tags": ["d4_d5", "semi_fechadas", "flanco"], "difficulty": 4 },
        { "title": "GM Repertoire 12: A Benoni Moderna (Petrov)", "min": 2000, "max": 2600, "tags": ["semi_fechadas"], "difficulty": 4 },
        { "title": "GM Repertoire 13: A Espanhola Aberta (Mikhalevski)", "min": 2000, "max": 2600, "tags": ["e4_e5"], "difficulty": 4 },
        { "title": "GM Repertoire 14: A Defesa Francesa Vol 1 (Berg)", "min": 2000, "max": 2600, "tags": ["francesa"], "difficulty": 4 },
        { "title": "GM Repertoire 15: A Defesa Francesa Vol 2 (Berg)", "min": 2000, "max": 2600, "tags": ["francesa"], "difficulty": 4 },
        { "title": "GM Repertoire 16: A Defesa Francesa Vol 3 (Berg)", "min": 2000, "max": 2600, "tags": ["francesa"], "difficulty": 4 },
        { "title": "GM Repertoire 17: A Eslava Clássica (Avrukh)", "min": 2000, "max": 2600, "tags": ["d4_d5"], "difficulty": 4 },
        { "title": "GM Repertoire 18: A Siciliana Sveshnikov (Kotronias)", "min": 2000, "max": 2600, "tags": ["siciliana"], "difficulty": 4 },
        { "title": "GM Repertoire 19: A Siciliana Dragão Vol 1 (Jones)", "min": 2000, "max": 2600, "tags": ["siciliana"], "difficulty": 4 },
        { "title": "GM Repertoire 20: A Semi-Eslava (Schandorff)", "min": 2000, "max": 2600, "tags": ["d4_d5"], "difficulty": 4 },
        { "title": "GM Repertoire 21: A Siciliana Dragão Vol 2 (Jones)", "min": 2000, "max": 2600, "tags": ["siciliana"], "difficulty": 4 },
        { "title": "GM Repertoire: A Defesa Pirc (Marin)", "min": 2000, "max": 2600, "tags": ["semi_abertas"], "difficulty": 4 },
        { "title": "GM Repertoire: A Defesa Berlinesa (Roiz)", "min": 2000, "max": 2600, "tags": ["e4_e5"], "difficulty": 4 },
        { "title": "Starting Out: 1.d4! (Cox)", "min": 1200, "max": 1800, "tags": ["repertorio_completo", "d4_d5", "india_rei", "semi_fechadas"], "difficulty": 1 },
        { "title": "Starting Out: 1.e4! (McDonald)", "min": 1200, "max": 1800, "tags": ["repertorio_completo", "e4_e5", "siciliana", "francesa", "caro_kann"], "difficulty": 1 },
        { "title": "Starting Out: Aberturas Abertas (Flear)", "min": 1200, "max": 1800, "tags": ["e4_e5"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Caro-Kann (Jacobs)", "min": 1200, "max": 1800, "tags": ["caro_kann"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Francesa (Jacobs)", "min": 1200, "max": 1800, "tags": ["francesa"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Holandesa (McDonald)", "min": 1200, "max": 1800, "tags": ["semi_fechadas"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Indiana do Rei (Gallagher/Ward)", "min": 1200, "max": 1800, "tags": ["india_rei"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Grünfeld (Gallagher)", "min": 1200, "max": 1800, "tags": ["grunfeld"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Nimzo-Indiana (Ward)", "min": 1200, "max": 1800, "tags": ["semi_fechadas"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Pirc/Moderna (Gallagher/Davies)", "min": 1200, "max": 1800, "tags": ["semi_abertas"], "difficulty": 1 },
        { "title": "Starting Out: A Defesa Siciliana (Emms)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: A Abertura Inglesa (Ward)", "min": 1200, "max": 1800, "tags": ["inglesa", "flanco"], "difficulty": 1 },
        { "title": "Starting Out: A Abertura Réti (McDonald)", "min": 1200, "max": 1800, "tags": ["flanco"], "difficulty": 1 },
        { "title": "Starting Out: A Partida Escocesa (Emms)", "min": 1200, "max": 1800, "tags": ["e4_e5"], "difficulty": 1 },
        { "title": "Starting Out: Gambito da Dama Aceito (Raetsky/Chetverik)", "min": 1200, "max": 1800, "tags": ["d4_d5"], "difficulty": 1 },
        { "title": "Starting Out: Defesas Eslava e Semi-Eslava (Flear)", "min": 1200, "max": 1800, "tags": ["d4_d5"], "difficulty": 1 },
        { "title": "Starting Out: Indiana da Dama (Greet)", "min": 1200, "max": 1800, "tags": ["semi_fechadas"], "difficulty": 1 },
        { "title": "Starting Out: Siciliana Clássica (Palliser)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: Siciliana Najdorf (Palliser)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: Siciliana Sveshnikov (Cox)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: Siciliana Dragão (Martin)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: Siciliana c3 (Emms)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: Ataque Grand Prix (Jones)", "min": 1200, "max": 1800, "tags": ["siciliana"], "difficulty": 1 },
        { "title": "Starting Out: O Sistema Colle (Palliser)", "min": 1200, "max": 1800, "tags": ["d4_d5", "semi_fechadas"], "difficulty": 1 },
        { "title": "Starting Out: A Benoni Moderna (Vegh)", "min": 1200, "max": 1800, "tags": ["semi_fechadas"], "difficulty": 1 },
        { "title": "Xadrez Vitorioso - Vol. 1-4 (Seirawan)", "min": 1400, "max": 2000, "tags": ["repertorio_completo"], "difficulty": 1, "synopsis": "A popular série de Yasser Seirawan (Aberturas, Táticas, Estratégias) cobre todos os fundamentos do jogo de uma forma muito didática, ideal para quem está começando a levar o xadrez a sério." }
    ],
    "Estratégia": [
        { "title": "How to Reassess Your Chess, 4th Edition", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Um clássico moderno que ensina jogadores de clube a entender e explorar desequilíbrios posicionais. Silman apresenta um método de pensamento para encontrar o plano certo em qualquer posição." },
        { "title": "Secrets of Modern Chess Strategy", "min": 2000, "max": 2600, "difficulty": 3, "synopsis": "John Watson explora a evolução da estratégia de xadrez desde Nimzowitsch, discutindo como conceitos modernos como o dinamismo e a regra-independência mudaram o jogo." },
        { "title": "Chess Structures: A Grandmaster Guide", "min": 2000, "max": 2600, "difficulty": 4, "synopsis": "Mauricio Flores Rios aborda o meio-jogo através da lente de estruturas de peões. O livro ensina os planos e ideias típicos para as estruturas mais comuns que surgem das aberturas." },
        { "title": "Winning Chess Strategies", "min": 1200, "max": 1800, "difficulty": 1, "synopsis": "Yasser Seirawan torna os conceitos estratégicos (postos avançados, colunas abertas, peças menores, etc.) acessíveis e fáceis de entender para jogadores em desenvolvimento." },
        { "title": "Python Strategy", "min": 2000, "max": 2600, "difficulty": 3, "synopsis": "Tigran Petrosian, o 'Iron Tigran', era um gênio da profilaxia e do jogo posicional. Neste livro, você aprenderá a arte de estrangular o oponente e antecipar seus planos." },
        { "title": "Understading Pawn Play in Chess", "min": 1600, "max": 2200, "difficulty": 2, "synopsis": "Drazen Marovic oferece um guia completo sobre o jogo de peões, cobrindo temas como peões passados, ilhas de peões, rupturas e a importância das estruturas de peões." },
        { "title": "Estratégia – Pachman", "min": 1800, "max": 2400, "difficulty": 2 },
        { "title": "Winning Chess Middlegames", "min": 1600, "max": 2200, "difficulty": 1 },
        { "title": "Manual Completo de Jogo Posicional – Escola Russa", "min": 1800, "max": 2400, "difficulty": 2 }
    ],
    "Cursos Online": [
        { "title": "Level 1-3 (Beginner)", "min": 0, "max": 1200, "difficulty": 1, "synopsis": "Cursos introdutórios do Chess King Learn para iniciantes. Ensinam as regras, movimentos, mates básicos e temas táticos fundamentais." },
        { "title": "Level 4-6 (Intermediate)", "min": 1200, "max": 1600, "difficulty": 2, "synopsis": "Para jogadores intermediários, estes cursos do Chess King aprofundam a tática, introduzem a estratégia e cobrem finais mais complexos." },
        { "title": "Level 7-9 (Advanced)", "min": 1600, "max": 2100, "difficulty": 3, "synopsis": "Cursos avançados do Chess King para jogadores de clube fortes, focando em jogo posicional, cálculo e técnica de finais." },
        { "title": "CT-ART 4.0 (Chess Tactics 1200-2400 ELO)", "min": 1200, "max": 2400, "difficulty": 2, "synopsis": "Um dos softwares de treinamento tático mais famosos e eficazes. Contém milhares de exercícios classificados por tema e dificuldade." },
        { "title": "Chess Tactics for Beginners", "min": 800, "max": 1200, "difficulty": 1, "synopsis": "Um curso focado em ensinar os padrões táticos mais básicos, como garfos, cravadas e ataques duplos, para jogadores que estão começando." },
        { "title": "Chess Endings for Beginners", "min": 800, "max": 1200, "difficulty": 1, "synopsis": "Introduz os mates elementares (Rei e Dama vs Rei, etc.) e os finais de peões mais fundamentais. Essencial para construir uma base sólida." },
        { "title": "Chess Strategy for Beginners", "min": 1000, "max": 1600, "difficulty": 2, "synopsis": "Explica os conceitos estratégicos básicos, como o controle do centro, o desenvolvimento das peças e a segurança do rei, de uma forma fácil de entender." },
        { "title": "Total Chess Endgames (1600-2400 ELO)", "min": 1600, "max": 2400, "difficulty": 3, "synopsis": "Um curso interativo que cobre todos os finais teóricos e práticos essenciais, do básico ao avançado, com exercícios para testar o conhecimento." },
        { "title": "Mikhail Tal - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3, "synopsis": "Um curso dedicado ao estilo e às partidas do oitavo campeão mundial, Mikhail Tal, o 'Mágico de Riga', famoso por seu jogo de ataque e sacrifícios intuitivos." },
        { "title": "Garry Kasparov - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3, "synopsis": "Estude as partidas e o estilo do 13º campeão mundial, Garry Kasparov, conhecido por sua preparação de aberturas profunda, jogo dinâmico e vontade de vencer." },
        { "title": "Chess: Year 1", "min": 0, "max": 1000, "difficulty": 1 },
        { "title": "Complete Chess Course 1", "min": 0, "max": 1000, "difficulty": 1 },
        { "title": "Learn Chess: From Beginner to Club Player", "min": 0, "max": 1500, "difficulty": 1 },
        { "title": "Mate in 1 (Chess Puzzles)", "min": 0, "max": 1000, "difficulty": 1 },
        { "title": "Mate in 2 (Simple puzzles)", "min": 800, "max": 1200, "difficulty": 1 },
        { "title": "Elementary Chess Tactics 1", "min": 800, "max": 1200, "difficulty": 1 },
        { "title": "Beginner Tactics Themes 1", "min": 800, "max": 1200, "difficulty": 1 },
        { "title": "Elementary Chess Tactics 2", "min": 800, "max": 1200, "difficulty": 1 },
        { "title": "Beginner Tactics Themes 2", "min": 800, "max": 1200, "difficulty": 1 },
        { "title": "Capturing Pieces 1 (Chess Puzzles)", "min": 0, "max": 800, "difficulty": 1 },
        { "title": "Capturing Pieces 2 (Chess Puzzles)", "min": 0, "max": 1000, "difficulty": 1 },
        { "title": "Chess School for Beginners", "min": 0, "max": 800, "difficulty": 1 },
        { "title": "Mate in 1 (Basic puzzles)", "min": 0, "max": 1000, "difficulty": 1 },
        { "title": "Chess Opening Ideas. Open Games 1.e4 e5", "min": 1000, "max": 1600, "tags": ["e4_e5"], "difficulty": 1 },
        { "title": "Chess Opening Ideas. Semi-Open Games 1.e4 non-e5", "min": 1000, "max": 1600, "tags": ["siciliana", "francesa", "caro_kann", "semi_abertas"], "difficulty": 1 },
        { "title": "Chess Opening Ideas. Closed Games 1.d4 or 1.Nf3", "min": 1000, "max": 1600, "tags": ["d4_d5", "india_rei", "grunfeld", "semi_fechadas", "inglesa", "flanco"], "difficulty": 1 },
        { "title": "Chess Opening Blunders", "min": 1000, "max": 1600, "tags": ["repertorio_completo"], "difficulty": 1 },
        { "title": "Chess: Year 2", "min": 1000, "max": 1400, "difficulty": 2 },
        { "title": "Chess: Year 3", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Art Of Defense", "min": 1400, "max": 2000, "difficulty": 2 },
        { "title": "Chess Tactics Art (1400-1600 ELO)", "min": 1400, "max": 1600, "difficulty": 2 },
        { "title": "CT-ART. Chess Mate Theory", "min": 1000, "max": 1600, "difficulty": 2 },
        { "title": "Simple Defense (Chess Puzzles)", "min": 1200, "max": 1800, "difficulty": 2 },
        { "title": "Mate in 2 (Easy puzzles)", "min": 1000, "max": 1400, "difficulty": 2 },
        { "title": "Mate in 3 (Difficult puzzles)", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Mate in 4 (Hard puzzles)", "min": 1400, "max": 1800, "difficulty": 2 },
        { "title": "Complete Chess Course 2", "min": 1000, "max": 1400, "difficulty": 2 },
        { "title": "Complete Chess Course 3", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Mate in 2 (Chess Puzzles)", "min": 1000, "max": 1400, "difficulty": 2 },
        { "title": "Mate in 3-4 (Chess Puzzles)", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Intermediate Tactics Themes 1", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Chess Opening Blunders 2", "min": 1200, "max": 1800, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Chess Opening Lab (1400-2000)", "min": 1400, "max": 2000, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Mate in 2 (Openings 2)", "min": 1200, "max": 1600, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Manual of Chess Combinations", "min": 1200, "max": 1800, "difficulty": 2 },
        { "title": "Chess Combinations Vol. 1", "min": 1400, "max": 1800, "difficulty": 2 },
        { "title": "Intermediate Tactics Themes 2", "min": 1200, "max": 1600, "difficulty": 2 },
        { "title": "Defense and counter attack", "min": 1400, "max": 2000, "difficulty": 2 },
        { "title": "Chess Middlegame I", "min": 1200, "max": 1800, "difficulty": 2 },
        { "title": "Mate in 2 (Openings 1)", "min": 1200, "max": 1600, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Modern Chess Openings 1 - Open Games (1. e4 e5)", "min": 1400, "max": 2000, "tags": ["e4_e5"], "difficulty": 2 },
        { "title": "Modern Chess Openings 2 - Semi-Open Games (1. e4)", "min": 1400, "max": 2000, "tags": ["siciliana", "francesa", "caro_kann", "semi_abertas"], "difficulty": 2 },
        { "title": "Modern Chess Openings 3 - Sicilian Defense (1. e4 c5)", "min": 1400, "max": 2000, "tags": ["siciliana"], "difficulty": 2 },
        { "title": "Modern Chess Openings 4 - Semi-Closed Games (1. d4 Nf6 2. c4 g6)", "min": 1400, "max": 2000, "tags": ["india_rei", "grunfeld"], "difficulty": 2 },
        { "title": "Modern Chess Openings 5 - Semi-Closed Games (1. d4 Nf6 2. c4 e6)", "min": 1400, "max": 2000, "tags": ["semi_fechadas"], "difficulty": 2 },
        { "title": "Modern Chess Openings 6 - Closed Games (1. d4 d5)", "min": 1400, "max": 2000, "tags": ["d4_d5"], "difficulty": 2 },
        { "title": "Modern Chess Openings 7 - Other", "min": 1400, "max": 2000, "tags": ["inglesa", "flanco"], "difficulty": 2 },
        { "title": "Universal Chess Opening: 1. d4 2. Nf3 3. e3", "min": 1400, "max": 2000, "tags": ["d4_d5", "semi_fechadas"], "difficulty": 2 },
        { "title": "Chess: a Positional Opening Repertoire", "min": 1400, "max": 2000, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Chess: An Aggressive Opening Repertoire", "min": 1400, "max": 2000, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Chess Tactics in Sicilian Defense 1", "min": 1400, "max": 2000, "tags": ["siciliana"], "difficulty": 2 },
        { "title": "Chess Tactics in French Defense", "min": 1400, "max": 2000, "tags": ["francesa"], "difficulty": 2 },
        { "title": "Chess Tactics in Caro-Kann Defense", "min": 1400, "max": 2000, "tags": ["caro_kann"], "difficulty": 2 },
        { "title": "Chess Tactics in Scandinavian Defense", "min": 1400, "max": 2000, "tags": ["semi_abertas"], "difficulty": 2 },
        { "title": "Chess Tactics in Open Games", "min": 1400, "max": 2000, "tags": ["e4_e5"], "difficulty": 2 },
        { "title": "Chess Tactics in Slav Defense", "min": 1400, "max": 2000, "tags": ["d4_d5"], "difficulty": 2 },
        { "title": "Important Opening Techniques", "min": 1400, "max": 2000, "tags": ["repertorio_completo"], "difficulty": 2 },
        { "title": "Chess Strategy & Tactics Vol. 2 (1800-2200 ELO)", "min": 1800, "max": 2200, "difficulty": 3 },
        { "title": "Chess Strategy & Tactics Vol. 1 (1600-2000 ELO)", "min": 1600, "max": 2000, "difficulty": 3 },
        { "title": "Chess Strategy (1800-2400)", "min": 1800, "max": 2400, "difficulty": 3 },
        { "title": "Chess Tactics Art (1600-1800 ELO)", "min": 1600, "max": 1800, "difficulty": 3 },
        { "title": "Advanced Defense (Chess Puzzles)", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Mate Studies", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Chess Combinations Vol. 2", "min": 1600, "max": 2000, "difficulty": 3 },
        { "title": "Chess Endgame Studies", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Chess Middlegame II", "min": 1400, "max": 2000, "difficulty": 3 },
        { "title": "Chess Middlegame III", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Chess Tactics in Sicilian Defense 2", "min": 1600, "max": 2200, "tags": ["siciliana"], "difficulty": 3 },
        { "title": "Chess Tactics in Grünfeld Defense", "min": 1600, "max": 2200, "tags": ["grunfeld"], "difficulty": 3 },
        { "title": "Chess Tactics in King's Indian Defense", "min": 1600, "max": 2200, "tags": ["india_rei"], "difficulty": 3 },
        { "title": "Chess Tactics in Volga Gambit", "min": 1600, "max": 2200, "tags": ["semi_fechadas"], "difficulty": 3 },
        { "title": "Encyclopedia Chess Combinations Vol. 1 Informant", "min": 1400, "max": 2000, "difficulty": 3 },
        { "title": "Encyclopedia Chess Combinations Vol. 2 Informant", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Manual of Chess Strategy, volume 1", "min": 1600, "max": 2200, "difficulty": 3 },
        { "title": "Alexander Alekhine - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Emanuel Lasker - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Jose Raul Capablanca - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Wilhelm Steinitz - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Max Euwe - World Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Henrique Mecking – Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Bobby Fischer - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Sergey Karjakin - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Magnus Carlsen - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Viswanathan Anand - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Vladimir Kramnik - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Mikhail Botvinnik - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Paul Morphy - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Nepomniachtchi Ian - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Anatoly Karpov - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Dīng Lìrén - Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Hikaru Nakamura - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Fabiano Caruana - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Alireza Firouzja – Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Levon Aronian - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Tigran Petrosian - World Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Boris Spassky - World Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Vasily Smyslov - World Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Viktor Korchnoi - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "David Bronstein - Elite Chess Player", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Dommaraju Gukesh – Chess Champion", "min": 1500, "max": 9999, "difficulty": 3 },
        { "title": "Chess Middlegame IV", "min": 1800, "max": 2400, "difficulty": 4 },
        { "title": "Chess Middlegame V", "min": 2000, "max": 9999, "difficulty": 4 },
        { "title": "Encyclopedia Chess Combinations Vol. 3 Informant", "min": 1800, "max": 9999, "difficulty": 4 },
        { "title": "Manual of Chess Strategy, volume 2", "min": 1800, "max": 2400, "difficulty": 4 }
    ]
};
